import fs from 'node:fs';
import path from 'node:path';

const SPANISH_DICT = {
  'page.title': 'Diagrama de {title}',
  'diagram.description.architecture': 'Diagrama de arquitectura del sistema generado por Archify.',
  'diagram.description.workflow': 'Diagrama de flujo de trabajo generado por Archify.',
  'diagram.description.sequence': 'Diagrama de secuencia del sistema generado por Archify.',
  'diagram.description.dataflow': 'Diagrama de flujo de datos generado por Archify.',
  'diagram.description.lifecycle': 'Diagrama de ciclo de vida generado por Archify.',
  'node.focus': 'Enfocar {label}',
  'node.focus.detail': 'Enfocar {label}, {detail}',
  'node.context.architecture': 'Componente de arquitectura',
  'node.context.workflow': 'Nodo de flujo de trabajo',
  'node.context.sequence': 'Participante de secuencia',
  'node.context.dataflow': 'Nodo de flujo de datos',
  'node.context.lifecycle': 'Estado de ciclo de vida',
  'legend.title': 'Leyenda',

  'legend.architecture.frontend': 'Frontend',
  'legend.architecture.backend': 'Backend',
  'legend.architecture.database': 'Base de datos',
  'legend.architecture.cloud': 'Servicio Cloud',
  'legend.architecture.security': 'Seguridad',
  'legend.architecture.messagebus': 'Bus de mensajes',
  'legend.architecture.external': 'Sistema externo',

  'legend.workflow.frontend': 'Interfaz de usuario',
  'legend.workflow.backend': 'Lógica backend',
  'legend.workflow.security': 'Políticas',
  'legend.workflow.messagebus': 'Acción de herramienta',
  'legend.workflow.database': 'Contexto / Traza',
  'legend.workflow.cloud': 'Servicio Cloud',
  'legend.workflow.external': 'Sistema externo',

  'legend.sequence.emphasis': 'petición principal',
  'legend.sequence.return': 'respuesta / retorno',
  'legend.sequence.security': 'validación de seguridad',
  'legend.sequence.dashed': 'traza asíncrona',
  'legend.sequence.default': 'mensaje estándar',

  'legend.dataflow.emphasis': 'datos principales',
  'legend.dataflow.security': 'política / datos sensibles',
  'legend.dataflow.dashed': 'lote asíncrono',
  'legend.dataflow.database': 'almacén de datos',
  'legend.dataflow.default': 'flujo de datos',

  'legend.lifecycle.start': 'inicio',
  'legend.lifecycle.active': 'estado activo',
  'legend.lifecycle.waiting': 'en espera',
  'legend.lifecycle.decision': 'decisión',
  'legend.lifecycle.success': 'éxito terminal',
  'legend.lifecycle.failure': 'fallo / salida',
  'legend.lifecycle.neutral': 'estado neutral',
  'legend.lifecycle.external': 'estado externo',

  'viewer.kind.frontend': 'Frontend',
  'viewer.kind.backend': 'Backend',
  'viewer.kind.database': 'Base de Datos',
  'viewer.kind.cloud': 'Cloud',
  'viewer.kind.security': 'Seguridad',
  'viewer.kind.messagebus': 'Bus de mensajes',
  'viewer.kind.external': 'Externo',
  'viewer.kind.neutral': 'Neutral',
  'viewer.kind.node': 'Nodo',
  'viewer.kind.start': 'Inicio',
  'viewer.kind.active': 'Activo',
  'viewer.kind.waiting': 'En espera',
  'viewer.kind.decision': 'Decisión',
  'viewer.kind.success': 'Éxito',
  'viewer.kind.failure': 'Fallo',

  'viewer.toolbar.actions': 'Acciones del diagrama',
  'viewer.theme.toggle.title': 'Cambiar tema claro/oscuro (T)',
  'viewer.theme.toggle': 'Cambiar tema de color',
  'viewer.theme.dark': 'Oscuro',
  'viewer.theme.light': 'Claro',

  'viewer.preset.choose.title': 'Elegir estilo visual (tecla S)',
  'viewer.preset.choose': 'Elegir estilo visual',
  'viewer.preset.style': 'Estilo',
  'viewer.preset.menu': 'Estilo visual',
  'viewer.preset.identity': 'Identidad visual',
  'viewer.preset.cycles': 'Alternar con tecla S',
  'viewer.preset.classic': 'Clásico',
  'viewer.preset.classic.short': 'Clásico',
  'viewer.preset.classic.hint': 'Estándar técnico estable',
  'viewer.preset.flow': 'Flujo de Señales',
  'viewer.preset.flow.short': 'Flujo',
  'viewer.preset.flow.hint': 'Presentación dinámica y animada',
  'viewer.preset.blueprint': 'Plano Técnico',
  'viewer.preset.blueprint.hint': 'Revisión técnica de ingeniería',
  'viewer.preset.editorial': 'Editorial',
  'viewer.preset.editorial.hint': 'Diseño para documentación ejecutiva',
  'viewer.preset.badge.signalFlow': 'FLUJO DE SEÑALES',
  'viewer.preset.badge.blueprint': 'PLANO TÉCNICO / REV 01',
  'viewer.preset.badge.editorial': 'EDITORIAL / REPORTE TÉCNICO',
  'viewer.preset.badge.editorialPlate': 'ARCHIFY / LÁMINA 04',
  'viewer.preset.current': 'Estilo visual: {style}. Elegir estilo visual',

  'viewer.motion.live': 'Dinámico',
  'viewer.motion.still': 'Estático',
  'viewer.motion.pause': 'Pausar animación',
  'viewer.motion.resume': 'Reanudar animación',
  'viewer.motion.reduced': 'Animación pausada por preferencia de movimiento reducido',
  'viewer.motion.hidden': 'Animación pausada mientras la pestaña está inactiva',
  'viewer.motion.yielding': 'Pausar animación; cediendo el control a {owner}',
  'viewer.motion.yielding.title': 'Vista previa activa · cediendo a {owner}',

  'viewer.owner.story': 'la historia guiada',
  'viewer.owner.chapter': 'el capítulo activo',
  'viewer.owner.chapterPreview': 'la vista previa de cambios de capítulo',
  'viewer.owner.handoff': 'el traspaso entre capítulos',
  'viewer.owner.route': 'la sonda de ruta',
  'viewer.owner.lens': 'la lente semántica',
  'viewer.owner.relationship': 'la vista previa de relaciones',
  'viewer.owner.intent': 'la traza de intención',
  'viewer.owner.focus': 'el enfoque semántico',
  'viewer.owner.legend': 'la vista previa de leyenda',
  'viewer.owner.reader': 'la interacción del usuario',

  'viewer.present.enter': 'Entrar a modo presentación',
  'viewer.present.enter.title': 'Modo presentación (tecla F)',
  'viewer.present.exit': 'Salir del modo presentación',
  'viewer.present.exit.title': 'Salir del modo presentación (tecla F o Escape)',
  'viewer.present.present': 'Presentar',
  'viewer.present.exit.label': 'Salir',

  'viewer.export.button': 'Exportar',
  'viewer.export.button.title': 'Exportar diagrama (tecla E)',
  'viewer.export.diagram': 'Exportar diagrama',
  'viewer.export.menu': 'Exportar',
  'viewer.export.subtitle': 'Formatos limpios y portables',
  'viewer.export.share': 'Compartir',
  'viewer.export.shareCard': 'Tarjeta de presentación',
  'viewer.export.routeShareCard': 'Tarjeta de ruta para compartir',
  'viewer.export.reachShareCard': 'Tarjeta de alcance para compartir',
  'viewer.export.copyShareCard': 'Copiar tarjeta al portapapeles',
  'viewer.export.copyDiagram': 'Copiar diagrama',
  'viewer.export.clipboardPng': 'Copiar PNG al portapapeles',
  'viewer.export.raster': 'Imágenes rasterizadas',
  'viewer.export.image': 'Imagen',
  'viewer.export.lossless': 'Imagen sin pérdida (PNG)',
  'viewer.export.compact': 'Imagen compacta (WebP)',
  'viewer.export.modern': 'Imagen moderna (AVIF)',
  'viewer.export.vectorMotion': 'Vector y animación',
  'viewer.export.vectorMotion.heading': 'Vector y animación',
  'viewer.export.editable': 'Vector editable (SVG)',
  'viewer.export.motion6s': 'Animación WebM de 6s',
  'viewer.export.unsupported': 'No compatible con este navegador',
  'viewer.export.clipboardUnsupported': 'Este navegador no permite copiar imágenes al portapapeles',
  'viewer.export.clipboardUnsupported.period': 'Este navegador no permite copiar imágenes al portapapeles.',
  'viewer.export.clipboardUnsupported.short': 'Copia al portapapeles no disponible en este navegador.',
  'viewer.export.motionUnavailable': 'Grabación de video no disponible en este navegador',
  'viewer.export.webmUnavailable': 'Formato WebM no compatible en este navegador',
  'viewer.export.failed': 'Error al exportar: {message}',
  'viewer.export.unknownVariant': 'Tipo de tarjeta desconocido: {variant}',
  'viewer.export.routeRequired': 'Traza una ruta antes de exportar una tarjeta de ruta',
  'viewer.export.reachRequired': 'Traza el alcance antes de exportar una tarjeta de alcance',
  'viewer.export.unknown': 'desconocido',
  'viewer.export.routeFailed': 'Error al exportar la tarjeta de ruta: {message}',
  'viewer.export.reachFailed': 'Error al exportar la tarjeta de alcance: {message}',
  'viewer.export.copyFailed': 'Error al copiar: {message}',
  'viewer.export.copiedPng': 'PNG copiado al portapapeles exitosamente',
  'viewer.export.copiedShare': 'Tarjeta copiada al portapapeles',
  'viewer.export.downloadedShare': 'Tarjeta descargada',
  'viewer.export.downloadedRoute': 'Tarjeta de ruta descargada',
  'viewer.export.downloadedReach': 'Tarjeta de alcance descargada',
  'viewer.export.downloadedWebm': 'Video WebM descargado',
  'viewer.export.recording': 'Grabando 6 segundos de animación…',
  'viewer.export.card.routeSummary.one': 'Ruta: {source} → {target} · {count} salto directo',
  'viewer.export.card.routeSummary.other': 'Ruta: {source} → {target} · {count} saltos directos',
  'viewer.export.card.reachSummary': 'Alcance {direction} desde {origin} · {nodes} · {links} · máx {hops}',
  'viewer.export.card.node.one': '{count} componente',
  'viewer.export.card.node.other': '{count} componentes',
  'viewer.export.card.link.one': '{count} conexión',
  'viewer.export.card.link.other': '{count} conexiones',
  'viewer.export.card.hop.one': '{count} salto',
  'viewer.export.card.hop.other': '{count} saltos',
  'viewer.export.card.routeBadge': 'ARCHIFY · RUTA · {hops}',
  'viewer.export.card.reachBadge': 'ARCHIFY · ALCANCE {direction}',
  'viewer.export.card.defaultBadge': 'ARCHIFY · {preset} · {theme}',
  'viewer.export.direction.upstream': 'Origen (entrante)',
  'viewer.export.direction.downstream': 'Destino (saliente)',
  'viewer.export.error.canvasUnavailable': 'Lienzo Canvas no disponible para {label}',
  'viewer.export.error.contextUnavailable': 'Contexto 2D no disponible para {label}',
  'viewer.export.error.toBlobUnavailable': 'Función canvas.toBlob no disponible para {label}',
  'viewer.export.error.toBlobNull': 'canvas.toBlob no generó datos para {label}',
  'viewer.export.error.variantsCombined': 'No se pueden combinar múltiples variantes de tarjeta',
  'viewer.export.error.viewerState': 'No se pudo limpiar el estado del visor para exportar la tarjeta',
  'viewer.export.error.routeState': 'No se pudo conservar la ruta al exportar la tarjeta',
  'viewer.export.error.reachState': 'No se pudo conservar el alcance al exportar la tarjeta',
  'viewer.export.error.webmRequirements': 'La exportación WebM requiere animación activa y soporte de MediaRecorder',
  'viewer.export.error.mediaRecorder': 'Falló la grabación de MediaRecorder',
  'viewer.export.error.emptyWebm': 'MediaRecorder generó un archivo WebM vacío',
  'viewer.export.error.webmBackground': 'No se pudo cargar el fondo SVG para la exportación WebM',

  'viewer.guided.region': 'Vistas guiadas del diagrama',
  'viewer.guided.previous': 'Vista guiada anterior',
  'viewer.guided.previous.title': 'Vista guiada anterior (tecla [)',
  'viewer.guided.next': 'Siguiente vista guiada',
  'viewer.guided.next.title': 'Siguiente vista guiada (tecla ])',
  'viewer.guided.views': 'Vistas guiadas',
  'viewer.guided.explore': 'Explora la arquitectura',
  'viewer.guided.intro': 'Navega por los flujos principales del sistema paso a paso.',
  'viewer.guided.trail': 'Trayectoria guiada',
  'viewer.guided.beat': 'Paso',
  'viewer.guided.nextBeat': 'Siguiente',
  'viewer.guided.play': 'Reproducir flujo guiado',
  'viewer.guided.play.title': 'Reproducir flujo guiado (tecla P)',
  'viewer.guided.pause': 'Pausar flujo guiado',
  'viewer.guided.pause.title': 'Pausar flujo guiado (tecla P)',
  'viewer.guided.replay': 'Repetir flujo guiado',
  'viewer.guided.replay.title': 'Repetir flujo guiado (tecla P)',
  'viewer.guided.playStory': 'Reproducir',
  'viewer.guided.pauseStory': 'Pausar',
  'viewer.guided.replayStory': 'Repetir',
  'viewer.guided.motionUnavailable': 'Reproducción no disponible en modo estático',
  'viewer.guided.enableMotion': 'Activa el modo dinámico para reproducir el recorrido guiado',
  'viewer.guided.selectBeatLink': 'Selecciona un paso para copiar su enlace directo',
  'viewer.guided.copyMoment': 'Copiar este punto',
  'viewer.guided.momentCopied': 'Enlace del momento copiado al portapapeles',
  'viewer.guided.momentCopyFailed': 'No se pudo copiar el enlace del momento',
  'viewer.guided.copied': 'Copiado',
  'viewer.guided.copyFailed': 'Error al copiar',
  'viewer.guided.showAll': 'Ver todo',
  'viewer.guided.showAll.aria': 'Mostrar el diagrama completo',
  'viewer.guided.chapters': 'Capítulos del flujo',
  'viewer.guided.storyTrail': 'Recorrido para {label}: {count} pasos',
  'viewer.guided.chapter.open': 'Abrir capítulo {index} de {total}: {label}, {count} paradas',
  'viewer.guided.chapter.current': 'Capítulo actual {index} de {total}: {label}, {count} paradas',
  'viewer.guided.chapter.selectedNodes': '{count} componentes seleccionados',
  'viewer.guided.chapter.stops': '{count} paradas',
  'viewer.guided.chapter.stop.one': '{count} parada',
  'viewer.guided.chapter.stop.other': '{count} paradas',
  'viewer.guided.chapter.current.title': '{label} — capítulo actual, {count} paradas',
  'viewer.guided.chapter.delta.expanded': '{stay} se mantienen, {enter} entran, {leave} salen',
  'viewer.guided.chapter.delta.aria': 'Abrir capítulo {index} de {total}: {label}. Cambio de enfoque: {delta}',
  'viewer.guided.chapter.delta.title': '{label} — cambio de enfoque {delta}',
  'viewer.guided.handoff': '{from} → {to} · vía {label}',
  'viewer.guided.share.chapter': 'Capítulo {index} / {total}',
  'viewer.guided.share.initial': 'Capítulo 01 / 01',
  'viewer.guided.share.default': 'Capítulo guiado',
  'viewer.guided.state.ready': 'Listo',
  'viewer.guided.state.playing': 'Reproduciendo',
  'viewer.guided.state.settled': 'Fijado',
  'viewer.guided.state.paused': 'Pausado',
  'viewer.guided.state.pinned': 'Anclado',
  'viewer.guided.state.still': 'Estático',
  'viewer.guided.share.step': 'Paso {index} / {total} · {label}',
  'viewer.guided.share.staticMoment': '{step} · Momento estático',
  'viewer.guided.share.complete': '{count} pasos completados · {note}',
  'viewer.guided.share.settled': 'Ruta fijada para lectura técnica.',
  'viewer.guided.share.staticPath': '{count} pasos · Ruta estática',
  'viewer.guided.share.ready': '{count} pasos · Listo',
  'viewer.guided.share.aria': '{state} capítulo {index} de {total}: {label}. {beat}. {route}',
  'viewer.guided.beat.start': 'Paso {index} / {total} · {label} · punto de partida',
  'viewer.guided.beat.forward': 'Paso {index} / {total} · {from} → {to}',
  'viewer.guided.beat.reverse': 'Paso {index} / {total} · {from} → {to} · enlace inverso',
  'viewer.guided.beat.multiple': 'Paso {index} / {total} · {from} ⇄ {to} · {count} enlaces',
  'viewer.guided.beat.group': 'Paso {index} / {total} · {from} · {to} · agrupados',
  'viewer.guided.beat.aria.prefix': 'Paso del flujo {index} de {total}: {label}. ',
  'viewer.guided.beat.aria.start': 'Punto de partida.',
  'viewer.guided.beat.aria.forward': 'Desde {from} a través de una relación dirigida hacia adelante.',
  'viewer.guided.beat.aria.reverse': 'Desde {from}; la relación original va en sentido contrario desde {to} hasta {from}.',
  'viewer.guided.beat.aria.multiple': 'Desde {from} mediante {count} relaciones dirigidas.',
  'viewer.guided.beat.aria.group': 'Agrupado con {from} sin conexión directa.',
  'viewer.guided.caption.start': 'Punto de inicio',
  'viewer.guided.caption.grouped': 'Transición en grupo · sin enlace directo',
  'viewer.guided.caption.more': ' +{count} más',
  'viewer.guided.caption.reverse': 'Relación en sentido inverso',
  'viewer.guided.caption.relationships': '{count} relaciones',
  'viewer.guided.caption.relationship': 'Relación dirigida',
  'viewer.guided.caption.direction': 'dirección: {from} → {to}',
  'viewer.guided.caption.starting': 'Punto de inicio',
  'viewer.guided.beatLink': 'Copiar enlace al punto actual: Paso {index} de {total}: {label}',
  'viewer.guided.noStory': 'Este diagrama no tiene una historia guiada configurada.',

  'viewer.guide.eyebrow': 'Guía interactiva',
  'viewer.guide.close': 'Cerrar guía interactiva',
  'viewer.guide.inspecting': 'Inspeccionando arquitectura del sistema',
  'viewer.guide.actions': 'Herramientas de análisis arquitectónico',
  'viewer.guide.find': 'Buscar cualquier componente',
  'viewer.guide.find.hint': 'Busca por etiquetas, tecnologías, capas o identificadores.',
  'viewer.guide.route': 'Trazar una ruta entre componentes',
  'viewer.guide.route.aria': 'Trazar ruta dirigida entre componentes',
  'viewer.guide.route.hint': 'Descubre cómo viajan los datos entre dos componentes cualesquiera.',
  'viewer.guide.map': 'Ver mapa completo (Radar)',
  'viewer.guide.map.hint': 'Abre el Radar Semántico con vista panorámica y componentes fijos.',
  'viewer.guide.lens': 'Comparar tipos de componentes (Lente)',
  'viewer.guide.lens.hint': 'Analiza el acoplamiento y las llamadas directas entre capas.',
  'viewer.guide.story': 'Reproducir historia paso a paso',
  'viewer.guide.story.hint': 'Navega por las vistas guiadas predefinidas para la defensa.',
  'viewer.guide.present': 'Activar Modo Presentación',
  'viewer.guide.present.hint': 'Maximiza el diagrama para proyectarlo en pantalla completa.',
  'viewer.guide.shortcuts': 'Atajos de teclado rápidos',
  'viewer.guide.shortcut.export': 'Exportar (E)',
  'viewer.guide.shortcut.theme': 'Tema (T)',
  'viewer.guide.shortcut.style': 'Estilo (S)',
  'viewer.guide.shortcut.reset': 'Restablecer (0)',
  'viewer.guide.shortcut.zoomIn': 'Acercar (+)',
  'viewer.guide.shortcut.zoomOut': 'Alejar (-)',
  'viewer.guide.shortcut.close': 'Cerrar (Esc)',
  'viewer.guide.facts': '{nodes} · {relationships} · {views}',
  'viewer.guide.fact.node.one': '{count} componente del sistema',
  'viewer.guide.fact.node.other': '{count} componentes del sistema',
  'viewer.guide.fact.relationship.one': '{count} conexión',
  'viewer.guide.fact.relationship.other': '{count} conexiones',
  'viewer.guide.fact.view.one': '{count} vista guiada',
  'viewer.guide.fact.view.other': '{count} vistas guiadas',
  'viewer.guide.story.available.one': 'Recorre {count} capítulo y sus conexiones reales.',
  'viewer.guide.story.available.other': 'Recorre {count} capítulos y sus conexiones reales.',
  'viewer.guide.story.unavailable': 'No hay historia guiada en este diagrama.',
  'viewer.guide.open': 'Abrir guía interactiva',
  'viewer.guide.noStory': 'Este diagrama no tiene historia guiada.',

  'viewer.finder.title': 'Buscador de componentes',
  'viewer.finder.close': 'Cerrar buscador',
  'viewer.finder.placeholder': 'Escribe para buscar componentes...',
  'viewer.finder.search': 'Buscar componentes del sistema',
  'viewer.finder.results': 'Componentes encontrados',
  'viewer.finder.empty': 'No se encontraron componentes coincidentes',
  'viewer.finder.result.focus': 'Enfocar {label}',
  'viewer.finder.result.routeStart': 'Elegir {label} como origen de ruta',
  'viewer.finder.result.routeTarget': 'Elegir {label} como destino de ruta, {links}',
  'viewer.finder.status.empty': 'Sin coincidencias',
  'viewer.finder.status.count.one': '{count} componente encontrado',
  'viewer.finder.status.count.other': '{count} componentes encontrados',
  'viewer.finder.noun.nodes': 'componentes',
  'viewer.finder.link.one': '{count} enlace',
  'viewer.finder.link.other': '{count} enlaces',
  'viewer.finder.result.focus.one': 'Enfocar {label}, {count} conexión',
  'viewer.finder.result.focus.other': 'Enfocar {label}, {count} conexiones',
  'viewer.finder.status.filtered': '{visible} de {available} {noun}',
  'viewer.finder.status.all': '{available} {noun}',

  'viewer.passport.eyebrow': 'Pasaporte Semántico',
  'viewer.passport.metadata': 'Metadatos técnicos',
  'viewer.passport.evidence': 'Evidencia de código fuente',
  'viewer.passport.verified': 'Fuente verificada',
  'viewer.passport.reach': 'Alcance de conexiones',
  'viewer.passport.reach.trace': 'Trazar dependencias y alcance',
  'viewer.passport.upstream': 'Componentes origen (hacia arriba)',
  'viewer.passport.downstream': 'Componentes destino (hacia abajo)',
  'viewer.passport.upstream.trace': 'Trazar dependencias entrantes',
  'viewer.passport.downstream.trace': 'Trazar dependencias salientes',
  'viewer.passport.close': 'Cerrar pasaporte semántico',
  'viewer.passport.copy': 'Copiar enlace',
  'viewer.passport.copy.focus': 'Copiar enlace al componente actual',
  'viewer.passport.relations': 'Conexiones directas',
  'viewer.passport.relations.show': 'Mostrar conexiones directas',
  'viewer.passport.relations.hide': 'Ocultar conexiones directas',
  'viewer.passport.relations.list': 'Lista de conexiones directas',
  'viewer.passport.copyRelation': 'Copiar conexión',
  'viewer.passport.copyNode': 'Copiar componente',
  'viewer.passport.copyPinned': 'Copiar enlace a conexión anclada',
  'viewer.passport.copySource': 'Copiar enlace al componente origen',
  'viewer.passport.copy.focused.success': 'Enlace del componente copiado',
  'viewer.passport.copy.pinned.success': 'Enlace de la conexión copiado',
  'viewer.passport.copy.focused.failed': 'No se pudo copiar el enlace',
  'viewer.passport.copy.pinned.failed': 'No se pudo copiar el enlace de la conexión',
  'viewer.passport.relationship.none': 'Sin conexiones directas',
  'viewer.passport.relationship.count.one': '{count} conexión',
  'viewer.passport.relationship.count.other': '{count} conexiones',
  'viewer.passport.relationship.show.one': 'Mostrar {count} conexión directa',
  'viewer.passport.relationship.show.other': 'Mostrar {count} conexiones directas',
  'viewer.passport.relationship.summary': '{out} salientes · {in} entrantes{loops}',
  'viewer.passport.relationship.loops': ' · {count} bucle propio',
  'viewer.passport.relationship.explorer': 'Explorador de conexiones directas',
  'viewer.passport.relationship.help': 'Usa las flechas del teclado para explorar relaciones. Presiona Enter o Espacio para fijar; Esc para salir.',
  'viewer.passport.relationship.loopsBack': 'bucle hacia sí mismo',
  'viewer.passport.relationship.connectsTo': 'conecta hacia',
  'viewer.passport.relationship.connectsFrom': 'recibe conexión desde',
  'viewer.passport.relationship.pinned': 'Conexión fijada · {from} → {to} · {label}',
  'viewer.passport.relationship.inspect': 'Inspeccionar conexión {index} de {total}: {from} a {to}, {label}. Presiona Enter para detalles.',
  'viewer.passport.relationship.group.out': 'Conexiones salientes',
  'viewer.passport.relationship.group.in': 'Conexiones entrantes',
  'viewer.passport.relationship.group.loop': 'Bucles internos',
  'viewer.passport.relationship.row': '{group}: {relationship}, {neighbor}',
  'viewer.passport.relationship.direction.out': 'SALIDA →',
  'viewer.passport.relationship.direction.in': '← ENTRADA',
  'viewer.passport.relationship.direction.loop': 'BUCLE',
  'viewer.passport.sourceCount.one': '{count} archivo de código fuente verificado',
  'viewer.passport.sourceCount.other': '{count} archivos de código fuente verificados',
  'viewer.passport.sourceMarker': 'CÓDIGO',
  'viewer.passport.beacon.one': '{count} fuente verificada; enfoca para inspeccionar',
  'viewer.passport.beacon.other': '{count} fuentes verificadas; enfoca para inspeccionar',
  'viewer.passport.repository.open': 'Abrir repositorio en revisión {revision}',
  'viewer.passport.source.open': 'Abrir archivo fuente {path} en revisión {revision}',
  'viewer.passport.source.openLink': 'Abrir ↗',
  'viewer.passport.reach.upstream.one': 'Trazar {count} componente entrante',
  'viewer.passport.reach.upstream.other': 'Trazar {count} componentes entrantes',
  'viewer.passport.reach.downstream.one': 'Trazar {count} componente saliente',
  'viewer.passport.reach.downstream.other': 'Trazar {count} componentes salientes',
  'viewer.passport.reach.noUpstream': 'No hay componentes entrantes',
  'viewer.passport.reach.noDownstream': 'No hay componentes salientes',
  'viewer.passport.reach.status': '{direction} · {nodes} componentes · {links} conexiones · máx {hops} saltos',

  'viewer.route.eyebrow': 'Sonda de rutas arquitectónicas',
  'viewer.route.start': 'Elige el componente de inicio',
  'viewer.route.start.find': 'Buscar origen',
  'viewer.route.start.find.aria': 'Buscar origen de ruta',
  'viewer.route.copy': 'Copiar enlace',
  'viewer.route.copy.aria': 'Copiar enlace a la ruta trazada',
  'viewer.route.clear': 'Limpiar',
  'viewer.route.clear.aria': 'Limpiar sonda de ruta',
  'viewer.route.traced': 'Ruta arquitectónica trazada',
  'viewer.route.pickTwo': 'Selecciona dos componentes en el diagrama',
  'viewer.route.pickOne': 'Selecciona un componente en el diagrama',
  'viewer.route.controls': 'Controles de recorrido de ruta',
  'viewer.route.previous': 'Posición previa',
  'viewer.route.play': 'Reproducir flujo',
  'viewer.route.pause': 'Pausar flujo',
  'viewer.route.replay': 'Repetir flujo',
  'viewer.route.next': 'Siguiente posición',
  'viewer.route.journey': 'Recorrido',
  'viewer.route.pause.label': 'Pausar',
  'viewer.route.replay.label': 'Repetir',
  'viewer.route.overview': 'Vista panorámica',
  'viewer.route.overview.aria': 'Mostrar vista panorámica de la ruta completa',
  'viewer.route.instructions': 'Selecciona el componente origen y luego el destino.',
  'viewer.route.destination': 'Elige el destino desde {label}',
  'viewer.route.destination.find': 'Buscar destino',
  'viewer.route.destination.find.aria': 'Buscar componente destino alcanzable',
  'viewer.route.differentDestination': 'Elige otro destino',
  'viewer.route.distinct': 'Se requieren dos componentes distintos para trazar una ruta.',
  'viewer.route.unreachable': 'No existe ruta directa hacia {label}',
  'viewer.route.unreachable.detail': '{target} no es alcanzable desde {source}. Selecciona un destino resaltado.',
  'viewer.route.start.instructions': 'Selecciona el componente de partida. Se iluminarán los destinos disponibles.',
  'viewer.route.copy.success': 'Enlace de la ruta copiado al portapapeles',
  'viewer.route.copy.failed': 'No se pudo copiar el enlace de la ruta',
  'viewer.route.position': 'Posición en ruta {index} de {total}: {label}',
  'viewer.route.step': 'Paso {index} de {total} · {phase} · {label}',
  'viewer.route.motionRequired': 'El recorrido automático requiere modo dinámico activado',
  'viewer.route.trigger.clear': 'Limpiar ruta trazada',
  'viewer.route.overview.status': '{nodes} · {hops} · ruta más directa',
  'viewer.route.overview.node.one': '{count} componente',
  'viewer.route.overview.node.other': '{count} componentes',
  'viewer.route.overview.hop.one': '{count} salto',
  'viewer.route.overview.hop.other': '{count} saltos',
  'viewer.route.phase.playing': 'En ejecución',
  'viewer.route.phase.complete': 'Finalizado',
  'viewer.route.phase.inspecting': 'Inspeccionando',
  'viewer.route.destination.count.one': '{count} destino disponible. Selecciona el componente resaltado.',
  'viewer.route.destination.count.other': '{count} destinos disponibles. Selecciona un componente resaltado.',
  'viewer.route.noOutgoing': 'No hay conexiones salientes desde este componente. Selecciona otro origen.',
  'viewer.route.result.title': '{source} hacia {target}',
  'viewer.route.finder.source.title': 'Elegir origen del flujo',
  'viewer.route.finder.source.placeholder': 'Buscar componentes origen...',
  'viewer.route.finder.source.empty': 'No hay componentes origen disponibles',
  'viewer.route.finder.source.results': 'Componentes que pueden iniciar un flujo',
  'viewer.route.finder.source.noun': 'orígenes posibles',
  'viewer.route.finder.source.badge': 'inicio',
  'viewer.route.finder.target.title': 'Destino alcanzable desde {label}',
  'viewer.route.finder.target.placeholder': 'Buscar destinos alcanzables...',
  'viewer.route.finder.target.empty': 'No hay destinos alcanzables',
  'viewer.route.finder.target.results': 'Destinos alcanzables',
  'viewer.route.finder.target.noun': 'destinos posibles',
  'viewer.route.hop.one': '{count} salto',
  'viewer.route.hop.other': '{count} saltos',

  'viewer.lens.eyebrow': 'Lente Semántica',
  'viewer.lens.title': 'Comparativa de Capas del Sistema',
  'viewer.lens.close': 'Cerrar lente semántica',
  'viewer.lens.instruction': 'Selecciona hasta dos capas para aislar su flujo de datos y dependencias.',
  'viewer.lens.kinds': 'Capas disponibles',
  'viewer.lens.choose': 'Selecciona una capa para ver sus componentes y tráfico.',
  'viewer.lens.copy': 'Copiar enlace de lente semántica',
  'viewer.lens.clear': 'Limpiar selección de capas',
  'viewer.lens.open': 'Abrir lente semántica',
  'viewer.lens.openActive': 'Abrir lente semántica activa',
  'viewer.lens.legend': 'Leyenda de capas',
  'viewer.lens.legend.inspect.one': 'Inspeccionar capa {label} ({count} componente)',
  'viewer.lens.legend.inspect.other': 'Inspeccionar capa {label} ({count} componentes)',
  'viewer.lens.kind.count.one': '{label}, {count} componente',
  'viewer.lens.kind.count.other': '{label}, {count} componentes',
  'viewer.lens.compare.one': '{first} → {second}: {forward} · {second} → {first}: {reverse} · {count} conexión directa',
  'viewer.lens.compare.other': '{first} → {second}: {forward} · {second} → {first}: {reverse} · {count} conexiones directas',
  'viewer.lens.single': '{nodes} · {relationships} · componentes vinculados visibles',
  'viewer.lens.node.one': '{count} componente de tipo {label}',
  'viewer.lens.node.other': '{count} componentes de tipo {label}',
  'viewer.lens.relationship.one': '{count} conexión directa',
  'viewer.lens.relationship.other': '{count} conexiones directas',

  'viewer.radar.title': 'Radar Semántico',
  'viewer.radar.building': 'Generando vista panorámica…',
  'viewer.radar.openFull': 'Abrir radar panorámico completo',
  'viewer.radar.open': 'Abrir radar',
  'viewer.radar.close': 'Cerrar radar',
  'viewer.radar.surface': 'Vista general del sistema. Haz clic en un componente para enfocarlo o arrastra para moverte.',
  'viewer.radar.click': 'Clic en nodo',
  'viewer.radar.drag': 'Arrastra para mover',
  'viewer.radar.space': 'El radar semántico requiere más espacio en pantalla.',
  'viewer.radar.nodes': 'Componentes en el radar',
  'viewer.radar.focus': 'Enfocar {label} desde el Radar',
  'viewer.radar.status': '{count} componentes · {viewport}',
  'viewer.radar.fullMap': '{count} componentes · vista completa',
  'viewer.radar.compacted': 'Radar compactado para optimizar visualización.',
  'viewer.radar.cancelWaiting': 'Cancelar espera de espacio para el radar',
  'viewer.radar.needsSpace': 'El radar semántico necesita mayor área visible',
  'viewer.radar.viewport.full': 'mapa total',
  'viewer.radar.viewport.width': '{percent}% de ancho',
  'viewer.radar.viewport.scale': 'escala al {percent}%',

  'viewer.nav.controls': 'Controles de navegación',
  'viewer.nav.route': 'Trazar ruta entre componentes',
  'viewer.nav.route.title': 'Trazar ruta (tecla R)',
  'viewer.nav.route.short': 'RUTA',
  'viewer.nav.radar': 'Abrir radar panorámico',
  'viewer.nav.radar.title': 'Radar panorámico (tecla M)',
  'viewer.nav.radar.short': 'MAPA',
  'viewer.nav.lens': 'Abrir comparativa de capas',
  'viewer.nav.lens.title': 'Comparar capas (tecla L)',
  'viewer.nav.lens.short': 'LENTE',
  'viewer.nav.find': 'Buscar componente',
  'viewer.nav.find.title': 'Buscar componente (tecla /)',
  'viewer.nav.guide': 'Abrir guía interactiva',
  'viewer.nav.guide.title': 'Guía interactiva (tecla ?)',
  'viewer.nav.zoomOut': 'Alejar vista',
  'viewer.nav.zoomOut.title': 'Alejar vista (tecla -)',
  'viewer.nav.reset': 'Restablecer vista',
  'viewer.nav.reset.title': 'Restablecer vista a escala inicial (tecla 0)',
  'viewer.nav.read': 'LEER',
  'viewer.nav.zoomIn': 'Acercar vista',
  'viewer.nav.zoomIn.title': 'Acercar vista (tecla +)',
  'viewer.nav.camera': '{hint}. Restablecer vista del diagrama',
  'viewer.nav.camera.title': '{semantic}{hint} · restablecer vista (0)',
  'viewer.nav.camera.semantic': 'Cámara semántica activa · ',
  'viewer.nav.level.map': 'MAPA',
  'viewer.nav.level.read': 'LEER',
  'viewer.nav.level.full': 'TOTAL',
  'viewer.nav.level.auto': 'AUTO',
  'viewer.nav.detail.map': 'Acércate para ver nombres de endpoints y protocolos',
  'viewer.nav.detail.read': 'Acércate más para ver detalles técnicos y notas',
  'viewer.nav.detail.full': 'Detalle arquitectónico completo',

  'viewer.intent.summary': '{label}. {out} conexiones salientes, {in} entrantes{loops}. {total} conexiones totales. Presiona Enter para ver detalles.',
  'viewer.intent.loops': ', {count} bucle propio',

  'viewer.common.copied': '¡Copiado!',
  'viewer.common.copyFailed': 'Error al copiar',
  'viewer.common.copyLink': 'Copiar enlace',
  'viewer.common.clear': 'Limpiar',
  'viewer.common.close': 'Cerrar'
};

// Verify all keys from archify_keys_en.json exist in SPANISH_DICT
const enKeys = JSON.parse(fs.readFileSync('./archify_keys_en.json', 'utf8'));
const missing = [];
for (const k of Object.keys(enKeys)) {
  if (!SPANISH_DICT[k]) {
    missing.push(k);
  }
}

if (missing.length > 0) {
  console.error('Missing translations for keys:', missing);
  process.exit(1);
}

// Validate placeholders
for (const [k, enVal] of Object.entries(enKeys)) {
  const esVal = SPANISH_DICT[k];
  const enMatches = (enVal.match(/\{[a-zA-Z0-9_]+\}/g) || []).sort();
  const esMatches = (esVal.match(/\{[a-zA-Z0-9_]+\}/g) || []).sort();
  if (JSON.stringify(enMatches) !== JSON.stringify(esMatches)) {
    console.error(`Placeholder mismatch in ${k}: expected ${enMatches} but got ${esMatches}`);
    process.exit(1);
  }
}

console.log('All 518 keys translated and placeholders verified 100%!');

// Now read the original archify-tool/archify/renderers/shared/i18n.mjs
const i18nPath = path.resolve('./archify-tool/archify/renderers/shared/i18n.mjs');
let i18nContent = fs.readFileSync(i18nPath, 'utf8');

// Replace SUPPORTED_LOCALES and DEFAULT_LOCALE
i18nContent = i18nContent.replace(
  "export const SUPPORTED_LOCALES = ['en', 'zh-CN'];\nexport const DEFAULT_LOCALE = 'en';",
  "export const SUPPORTED_LOCALES = ['es', 'en', 'zh-CN'];\nexport const DEFAULT_LOCALE = 'es';"
);

// Update each tuple in MESSAGE_PAIRS from ['en', 'zh-CN'] to ['es', 'en', 'zh-CN']
// Or replace the first string with Spanish if length is 2!
// Let's inspect the MESSAGE_PAIRS replacement:
// If we replace: 'key': ['en', 'zh'] -> 'key': [SPANISH, 'en', 'zh']
let replacedCount = 0;
for (const [k, esVal] of Object.entries(SPANISH_DICT)) {
  const keyEscaped = k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`('${keyEscaped}':\\s*\\[)(.*?)(\\],)`, 'g');
  i18nContent = i18nContent.replace(regex, (match, prefix, inner, suffix) => {
    replacedCount++;
    // inner is e.g. `'English text', 'Chinese text'`
    return `${prefix}${JSON.stringify(esVal)}, ${inner}${suffix}`;
  });
}

console.log(`Updated ${replacedCount} message pairs in i18n.mjs`);
fs.writeFileSync(i18nPath, i18nContent, 'utf8');

// Also update archify-tool/archify/schemas/common.schema.json to allow 'es' in locale enum
const commonSchemaPath = path.resolve('./archify-tool/archify/schemas/common.schema.json');
let commonSchema = fs.readFileSync(commonSchemaPath, 'utf8');
commonSchema = commonSchema.replace(
  '"locale": {\n      "enum": ["en", "zh-CN"]\n    }',
  '"locale": {\n      "enum": ["es", "en", "zh-CN"]\n    }'
);
fs.writeFileSync(commonSchemaPath, commonSchema, 'utf8');
console.log('common.schema.json updated with "es" locale!');
